### ISSUE TITLE
Extract metadata from `rounds` and `round_applications`

### ISSUE THREAD

**Issue by DistributedDoge** [davidgasquez/gitcoin-grants-data-portal#12]
Extracting `metadata` table to standarized columns is very handy, thanks for resolving #10 which does that for `projects` table. It feels natural to do the same for the remaining tables.

I took liberty to do the same for `rounds` here #11 mainly to get round titles.    

There is also `round_applications` which could use a similar treatment. If you want I can open a PR for that model as well.

**Comment by davidgasquez** [comment]
Closed by https://github.com/davidgasquez/gitcoin-grants-data-portal/pull/14
