### ISSUE TITLE
Add IPNS support

### ISSUE THREAD

**Issue by davidgasquez** [davidgasquez/gitcoin-grants-data-portal#18]
Offer a "pet name" way for people to access the latest tables.

- [x] IPNS
- [ ] ENS

**Comment by DistributedDoge** [comment]
`DNSlink` could [work](https://dnslink.dev/#introduction), although not every gateway supports it.

By setting `_dnslink DNS TXT` records one can make gateways resolve `cloudflare-ipfs.com/ipns/rounds.awesome-data.xyz` to whatever CID you are pinning latest copy of your data at.

**Comment by davidgasquez** [comment]
Thanks! 

DNSLink might a great solution. We can probably probably point a DNS TXT to IPNS which points to IPFS. A bit convoluted but will allow folks to do something like  `wget data.gitcoingrantsdataportal.com/rounds.parquet`.

Any ideas for a catchy domain name?

**Comment by davidgasquez** [comment]
IPNS done (for the data). Need to get `gitcoin-data.eth` and make it point to the IPNS record.


Feels quite convoluted tbh, but updating IPNS is free and updating ENS with each commit is not cheap.

**Comment by davidgasquez** [comment]
Closing this in favor of a more specific issue, #43
