### ISSUE TITLE
Support Allo `v2`

### ISSUE THREAD

**Issue by davidgasquez** [davidgasquez/gitcoin-grants-data-portal#39]

**Comment by DistributedDoge** [comment]
There is a graphQL playground to play with Allov2 schema and see some test projects folks put up there:

https://alloscan.spec.dev/graphiql

With next Gitcoin happening in April, and Grants Stack still using V1, might be best to wait a little and see what sort of infra would be in place by then before we attempt to index anything from there.

**Comment by davidgasquez** [comment]
Do you know if the [Indexer V2](https://grants-stack-indexer-v2.gitcoin.co/graphiql) also includes Allo V2?
